mysite/board/urls.py
from django.urls import path
from . import views

urlpatterns = [
    # path의 기본 경로 /board/
    path('', views.index, name='index'),
    # path('detail', views.detail, name='detail'), #/monitor/detail
    # path('delete', views.delete, name='delete'), #/monitor/delete
    # path('update', views.update, name='update'), #/monitor/update
]

mysite/common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = "common"
urlpatterns = [
    path("login/", auth_views.LoginView.as_view(template_name="common/login.html"), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("signup/", views.signup, name="signup"),
]

mysite/monitor/urls.py
from django.urls import path
from . import views

app_name = "monitor"
urlpatterns = [
    # path의 기본 경로 /monitor/
    path("", views.index, name="index"),
    path("bakFiles", views.bakFiles, name="bakFiles"),
    path('download/', views.file_download, name='file_download'),
    path("log", views.log, name="log"),
    path("auth", views.auth, name="auth"),
    path("rsyslogd", views.rsyslogd, name="rsyslogd"),
    path("sshd", views.sshd, name="sshd"),
    path("systemd", views.systemd, name="systemd"),
    path("postfix", views.postfix, name="postfix"),
    path("vsftpd", views.vsftpd, name="vsftpd"),
    path("tripwire", views.tripwire, name="tripwire"),
    path("todayLog/<str:log_name>", views.todayLog, name="todayLog"),
    path("history", views.history, name="history"),
    path("detail/<int:data_id>/", views.detail, name="detail"), #/monitor/detail
    # path("delete/<int:data_id>/", views.delete, name="delete"), #/monitor/delete
    # path("update/<int:data_id>", views.update, name="update"), #/monitor/update
]

mysite/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <title>PROJECT</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
  <!-- google fonts -->
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Jua&family=Nanum+Gothic:wght@700&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">

</head>
<body>

<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="{% url 'monitor:index'%}">Monitoring System</a>
    </div>
    <ul class="nav navbar-nav">
      <li><a href="{% url 'monitor:index'%}">Home</a></li>
      <li><a href="{% url 'monitor:bakFiles'%}">Backup List</a></li>
      <li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" href="#">Logs<span class="caret"></span></a>
        <ul class="dropdown-menu">
          <!--<li><a href="{% url 'monitor:auth'%}">auth</a></li>-->
          <li><a href="{% url 'monitor:postfix'%}">postfix</a></li>
          <li><a href="{% url 'monitor:rsyslogd'%}">rsyslogd</a></li>
          <li><a href="{% url 'monitor:sshd'%}">sshd</a></li>
          <li><a href="{% url 'monitor:systemd'%}">systemd</a></li>
     	  <li><a href="{% url 'monitor:vsftpd'%}">vsftpd</a></li>
      </ul>
      </li>
      <li><a href="{% url 'monitor:history'%}">History</a></li>
      <!-- <li><a href="{% url 'monitor:log'%}">예전꺼</a></li> -->
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <li><a href="{% url 'common:signup' %}"><span class="glyphicon glyphicon-user"></span> 회원가입</a></li>
      {% if user.is_authenticated %}
      <li><a href="{% url 'common:logout'%}"><span class="glyphicon glyphicon-log-out"></span>로그아웃</a></li>
      {% else %}
      <li><a href="{% url 'common:login'%}"><span class="glyphicon glyphicon-log-in"></span>로그인</a></li>
      {% endif %}
    </ul>
  </div>
</nav>
{%block content%}
{%endblock%}

mysite/templates/form_errors.html
{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}
            <div class="alert alert-danger">
                <strong> {{ field.label }} </strong>
                {{error}}
            </div>
        {%endfor%}
    {% endfor%}

    {% for error in form.non_field_errors %}
            <div class="alert alert-danger">
                <strong> {{ error }} </strong>
            </div>
    {% endfor %}
{%endif%}