mysite/board/urls.py
from django.urls import path
from . import views

urlpatterns = [
    # path의 기본 경로 /board/
    path('', views.index, name='index'),
    # path('detail', views.detail, name='detail'), #/monitor/detail
    # path('delete', views.delete, name='delete'), #/monitor/delete
    # path('update', views.update, name='update'), #/monitor/update
]

mysite/monitor/urls.py
from django.urls import path
from . import views

app_name = "monitor"
urlpatterns = [
    # path의 기본 경로 /monitor/
    path("", views.index, name="index"),
    path("bakFiles", views.bakFiles, name="bakFiles"),
    path('download/', views.file_download, name='file_download'),
    path("log", views.log, name="log"),
    path("auth", views.auth, name="auth"),
    path("rsyslogd", views.rsyslogd, name="rsyslogd"),
    path("sshd", views.sshd, name="sshd"),
    path("systemd", views.systemd, name="systemd"),
    path("postfix", views.postfix, name="postfix"),
    path("vsftpd", views.vsftpd, name="vsftpd"),
    path("tripwire", views.tripwire, name="tripwire"),
    path("todayLog/<str:log_name>", views.todayLog, name="todayLog"),
    path("history", views.history, name="history"),
    path("detail/<int:data_id>/", views.detail, name="detail"), #/monitor/detail
    # path("delete/<int:data_id>/", views.delete, name="delete"), #/monitor/delete
    # path("update/<int:data_id>", views.update, name="update"), #/monitor/update
]

mysite/monitor/models.py
from django.db import models


class SystemEvents(models.Model):
    CustomerID = models.CharField(max_length=1000, null=True)
    ReceivedAt = models.DateTimeField('ReceivedAt', null=True)
    DeviceReportedTime = models.DateTimeField('DeviceReportedTime', null=True)
    Facility = models.IntegerField(default=0, null=True)
    Priority = models.IntegerField(default=0, null=True)
    FromHost = models.CharField(max_length=1000, null=True)
    Message = models.CharField(max_length=1000, null=True)
    NTSeverity = models.IntegerField(default=0, null=True)
    Importance = models.IntegerField(default=0, null=True)
    EventSource = models.CharField(max_length=1000, null=True)
    EventUser = models.CharField(max_length=1000, null=True)
    EventCategory = models.IntegerField(default=0, null=True)
    EventID = models.IntegerField(default=0, null=True)
    EventBinaryData = models.CharField(max_length=1000, null=True)
    MaxAvailable = models.IntegerField(default=0, null=True)
    CurrUsage = models.IntegerField(default=0, null=True)
    MinUsage = models.IntegerField(default=0, null=True)
    MaxUsage = models.IntegerField(default=0, null=True)
    InfoUnitID = models.IntegerField(default=0, null=True)
    SysLogTag = models.CharField(max_length=1000, null=True)
    EventLogType = models.CharField(max_length=1000, null=True)
    GenericFileName = models.CharField(max_length=1000, null=True)
    SystemID = models.IntegerField(default=0, null=True)

    class Meta:
        db_table ='SystemEvents'


class SystemEventsProperties(models.Model):
    question = models.ForeignKey(SystemEvents, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    class Meta:
        db_table ='SystemEventsProperties'

# PROJECT
class Myauth(models.Model):
    date = models.CharField(max_length=100, null=True)
    host = models.CharField(max_length=100, null=True)
    process = models.CharField(max_length=100, null=True)
    message = models.CharField(max_length=1000, null=True)

    class Meta:
        db_table ='Myauth'


class Rsyslogd(models.Model):
    date = models.CharField(max_length=100, null=True)
    host = models.CharField(max_length=100, null=True)
    process = models.CharField(max_length=100, null=True)
    message = models.CharField(max_length=1000, null=True)

    class Meta:
        db_table ='Rsyslogd'


class Systemd(models.Model):
    date = models.CharField(max_length=100, null=True)
    host = models.CharField(max_length=100, null=True)
    process = models.CharField(max_length=100, null=True)
    message = models.CharField(max_length=1000, null=True)

    class Meta:
        db_table ='Systemd'


class Postfix(models.Model):
    date = models.CharField(max_length=100, null=True)
    host =  models.CharField(max_length=100, null=True)
    process = models.CharField(max_length=100, null=True)
    message = models.CharField(max_length=1000, null=True)

    class Meta:
        db_table ='Postfix'

class Vsftpd(models.Model):
    date = models.CharField(max_length=100, null=True)
    host = models.CharField(max_length=100, null=True)
    process = models.CharField(max_length=100, null=True)
    message = models.CharField(max_length=1000, null=True)

    class Meta:
        db_table ='Vsftpd'

class Tripwire(models.Model):
    date = models.CharField(max_length=100, null=True)
    host = models.CharField(max_length=100, null=True)
    process = models.CharField(max_length=100, null=True)
    message = models.CharField(max_length=1000, null=True)

    class Meta:
        db_table ='Tripwire'


class Sshd(models.Model):
    date = models.CharField(max_length=50, null=True)
    host = models.CharField(max_length=50, null=True)
    pid = models.CharField(max_length=50, null=True)
    message = models.CharField(max_length=1000, null=True)

    class Meta:
        db_table ='Sshd'

mysite/monitor/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from datetime import datetime
from django.utils.dateformat import DateFormat
from .models import SystemEvents, Myauth, Rsyslogd, Systemd, Postfix, Vsftpd, Sshd
import os
from django.core.paginator import Paginator
import mimetypes

from django.conf import settings
from django.http import HttpResponse


# @login_required(login_url="common:login")
def index(request):
    rsyslogs = SystemEvents.objects.order_by('-id')[:10]
    context = {'rsyslogs':rsyslogs}
    return render(request, "monitor/index.html", context)


# @login_required(login_url="common:login")
def log(request):
    rsyslogs = SystemEvents.objects.order_by('-id')[:10]
    context = {'rsyslogs':rsyslogs}
    return render(request, "monitor/log.html", context)


# @login_required(login_url="common:login")
def detail(request, data_id):
    # rsyslogs = [i for i in range(1, 25)]  # rsyslog 필드 24개
    # rsyslogs = SystemEvents.objects.filter(id=data_id)
    rsyslogs = SystemEvents.objects.get(id=data_id) # data_id 값만 가져오기
    context = {'rsyslogs':rsyslogs}
    return render(request, "monitor/detail.html", context)


#################### 로그 ####################
today = DateFormat(datetime.now()).format('Y-m-d')

#@login_required(login_url="common:login")
def auth(request):
    auth_log = Myauth.objects.all().order_by('-id')
    page = request.GET.get('page')
    paginator = Paginator(auth_log, 10) # 한 페이지 당 로그 10개
    page_obj = paginator.get_page(page)
    context = {'auth_log': auth_log, 'page_obj': page_obj}
    return render(request, "monitor/logs/auth.html", context)


#@login_required(login_url="common:login")
def rsyslogd(request):
    rsyslogd_log = Rsyslogd.objects.all().order_by('-id')
    page = request.GET.get('page')
    paginator = Paginator(rsyslogd_log, 10)
    page_obj = paginator.get_page(page)
    context = {'rsyslogd_log': rsyslogd_log, 'page_obj': page_obj}
    return render(request, "monitor/logs/rsyslogd.html", context)


#@login_required(login_url="common:login")
def systemd(request):
    systemd_log = Systemd.objects.all().order_by('-id')
    page = request.GET.get('page')
    paginator = Paginator(systemd_log, 10)
    page_obj = paginator.get_page(page)
    context = {'systemd_log': systemd_log, 'page_obj': page_obj}
    return render(request, "monitor/logs/systemd.html", context)


#@login_required(login_url="common:login")
def postfix(request):
    postfix_log = Postfix.objects.all().order_by('-id')
    page = request.GET.get('page')
    paginator = Paginator(postfix_log, 10)
    page_obj = paginator.get_page(page)
    context = {'postfix_log': postfix_log, 'page_obj': page_obj}
    return render(request, "monitor/logs/postfix.html", context)


#@login_required(login_url="common:login")
def vsftpd(request):
    vsftpd_log = Vsftpd.objects.all().order_by('-id')
    page = request.GET.get('page')
    paginator = Paginator(vsftpd_log, 10)
    page_obj = paginator.get_page(page)
    context = {'vsftpd_log': vsftpd_log, 'page_obj': page_obj}
    return render(request, "monitor/logs/vsftpd.html", context)


#@login_required(login_url="common:login")
def tripwire(request):
    tripwire_log = Tripwire.objects.all()
    context = {'tripwire_log': tripwire_log}
    return render(request, "monitor/logs/tripwire.html", context)


#@login_required(login_url="common:login")
def sshd(request):
    sshd_log = Sshd.objects.all().order_by('-id')
    page = request.GET.get('page')
    paginator = Paginator(sshd_log, 10)
    page_obj = paginator.get_page(page)
    context = {'sshd_log': sshd_log, 'page_obj': page_obj}
    return render(request, "monitor/logs/sshd.html", context)


# @login_required(login_url="common:login")
def todayLog(request, log_name):
    if log_name == "auth": log_name = "Myauth"
    log = log_name.objects.filter(date__startswith=today)
    context = {'log': log}
    return render(request, "monitor/logs/todayLog.html", context)



#################### 디렉터리 ####################
#@login_required(login_url="common:login")
def bakFiles(request):
    path = "/home/master/projects/mysite/media/backup"
    file_list = os.listdir(path)
    tar = [file for file in file_list if file.endswith(".tar.gz")]
    sql = [file for file in file_list if file.endswith(".sql")]
    file_list = tar + sql
    file_list.sort(reverse=True)
    # file_list_tar = [file for file in file_list if file.endswith(".log")]
    context = {'file_list': file_list}
    return render(request, "monitor/bakFiles.html", context)


#################### 파일다운로드 ####################
def file_download(request):
    path = request.GET['path']
    file_path = os.path.join(settings.MEDIA_ROOT, path)

    if os.path.exists(file_path):
        binary_file = open(file_path, 'rb')
        response = HttpResponse(binary_file.read(), content_type="application/octet-stream; charset=utf-8")
        response['Content-Disposition'] = 'attachment; filename=' + os.path.basename(file_path)
        return response
        # return render(request, "monitor/download.html", response)
    else:
        message = '알 수 없는 오류가 발생하였습니다.'
        return HttpResponse("<script>alert('" + message + "');history.back()'</script>")


#################### history ####################
def history(request):
    f = open("/home/master/projects/mysite/media/history/history.txt", "rb")
    # lines = f.readline()
    commands = []
    for line in f:
        line = line.rstrip()
        new2 = str(line)
        # new = line.decode('utf-8')
        # cat.insert(0, new)
        commands.insert(0, new2[2:-1])

    page = request.GET.get('page', '1')
    paginator = Paginator(commands[:50], 10)
    page_obj = paginator.get_page(page)

    context = {'page_obj': page_obj}
    f.close()
    return render(request, "monitor/history.html", context)

mysite/templates/monitor/bakFiles.html
{% extends 'base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
  <style>


  </style>

</head>
<body>
{% load static %}
{% block content %}
<div class="container">
  <h2 style="font-family: 'Jua', sans-serif;">백업한 파일 목록</h2>
  <br>

{% for file in file_list %}
  <ul>
    <li><a href="{% url 'monitor:file_download' %}?path={{ file }} ">{{ file }}</a></li>
  </ul>
{% endfor %}
</div>
{% endblock %}



</body>
</html>

mysite/templates/monitor/detail.html
{% extends 'base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{%block content%}
<div class="container">
    <h2>로그 관리 상세보기</h2>
    <p>#Rsyslog, #모니터링</p>
    <div class="table-responsive">
    <table class="table">
    <thead>
        <tr>
            <th>No.</th>
            <th>Attribute</th>
            <th>값</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>1</td>
            <td>id</td>
            <td>{{ rsyslogs.id }}</td>
        </tr>
        <tr>
            <td>2</td>
            <td>CustomerID</td>
            <td>{{ rsyslogs.CustomerID }}</td>
        </tr>
        <tr>
            <td>3</td>
            <td>ReceivedAt</td>
            <td>{{ rsyslogs.ReceivedAt }}</td>
        </tr>
        <tr>
            <td>4</td>
            <td>DeviceReportedTime</td>
            <td>{{ rsyslogs.DeviceReportedTime }}</td>
        </tr>
        <tr>
            <td>5</td>
            <td>Facility</td>
            <td>{{ rsyslogs.Facility }}</td>
        </tr>
        <tr>
            <td>6</td>
            <td>Priority</td>
            <td>{{ rsyslogs.Priority }}</td>
        </tr>
        <tr>
            <td>7</td>
            <td>FromHost</td>
            <td>{{ rsyslogs.FromHost }}</td>
        </tr>
        <tr>
            <td>8</td>
            <td>Message</td>
            <td>{{ rsyslogs.Message }}</td>
        </tr>
        <tr>
            <td>9</td>
            <td>NTSeverity</td>
            <td>{{ rsyslogs.NTSeverity }}</td>
        </tr>
        <tr>
            <td>10</td>
            <td>Importance</td>
            <td>{{ rsyslogs.Importance }}</td>
        </tr>
        <tr>
            <td>11</td>
            <td>EventSource</td>
            <td>{{ rsyslogs.EventSource }}</td>
        </tr>
        <tr>
            <td>12</td>
            <td>EventUser</td>
            <td>{{ rsyslogs.EventUser }}</td>
        </tr>
        <tr>
            <td>13</td>
            <td>EventCategory</td>
            <td>{{ rsyslogs.EventCategory }}</td>
        </tr>
        <tr>
            <td>14</td>
            <td>EventID</td>
            <td>{{ rsyslogs.EventID }}</td>
        </tr>
        <tr>
            <td>15</td>
            <td>EventBinaryData</td>
            <td>{{ rsyslogs.EventBinaryData }}</td>
        </tr>
        <tr>
            <td>16</td>
            <td>MaxAvailable</td>
            <td>{{ rsyslogs.MaxAvailable }}</td>
        </tr>
        <tr>
            <td>17</td>
            <td>CurrUsage</td>
            <td>{{ rsyslogs.CurrUsage }}</td>
        </tr>
        <tr>
            <td>18</td>
            <td>MinUsage</td>
            <td>{{ rsyslogs.MinUsage }}</td>
        </tr>
        <tr>
            <td>19</td>
            <td>MaxUsage</td>
            <td>{{ rsyslogs.MaxUsage }}</td>
        </tr>
        <tr>
            <td>20</td>
            <td>InfoUnitID</td>
            <td>{{ rsyslogs.InfoUnitID }}</td>
        </tr>
        <tr>
            <td>21</td>
            <td>SysLogTag</td>
            <td>{{ rsyslogs.SysLogTag }}</td>
        </tr>
        <tr>
            <td>22</td>
            <td>EventLogType</td>
            <td>{{ rsyslogs.EventLogType }}</td>
        </tr>
        <tr>
            <td>23</td>
            <td>GenericFileName</td>
            <td>{{ rsyslogs.GenericFileName }}</td>
        </tr>
        <tr>
            <td>24</td>
            <td>SystemID</td>
            <td>{{ rsyslogs.SystemID }}</td>
        </tr>


    </tbody>
</table>
{%endblock%}
  </div>
</div>
</body>
</html>

mysite/templates/monitor/history.html
{% extends 'base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
  <style>


  </style>

</head>
<body>
{% load static %}
{% load filter %}
{% block content %}
<div class="container">
  <h2 style="font-family: 'Jua', sans-serif;">history</h2>
  <p style="font-family: 'Nanum Gothic', sans-serif;">최근 실행한 명령어 50개</p>
  <br>

  <div class="table-responsive">
  <table class="table">
    <thead>
      <tr>
        <th>No.</th>
        <th>Command</th>
      </tr>
    </thead>
    <tbody>
{% for command in page_obj %}
      <tr>

        <td>{{ page_obj.paginator.count|sub:page_obj.start_index|sub:forloop.counter0|add:1}}</td>
        <td>{{ command }}</td>
      </tr>
{% endfor %}
    </tbody>
  </table>
    <!-- 페이징처리 시작 -->
    <ul class="pagination justify-content-center">
        <!-- 이전페이지 -->
        {% if page_obj.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}">이전</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
        </li>
        {% endif %}
        <!-- 페이지리스트 -->
        {% for page_number in page_obj.paginator.page_range %}
        {% if page_number == page_obj.number %}
        <li class="page-item active" aria-current="page">
            <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
        </li>
        {% else %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
        </li>
        {% endif %}
        {% endfor %}
        <!-- 다음페이지 -->
        {% if page_obj.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}">다음</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
        </li>
        {% endif %}
    </ul>
    <!-- 페이징처리 끝 -->
  </div>
</div>

{% endblock %}

</body>
</html>

mysite/templates/monitor/index.html
{% extends 'base.html' %}
<!DOCTYPE html>
<html lang="en">
{% load static %}
  <link rel="stylesheet" href="{% static 'css/fonts.css' %}">
<head>
</head>
{% block content %}
<body class="index">
<div class="container">
  <h2 style="font-family: 'Jua', sans-serif;">Log Monitoring System</h2>
  <br>
  <ul class="index" role="list" style="font-family: 'Nanum Gothic', sans-serif;">
    <li data-icon="1️⃣"> 메인 서버의 파일 및 디렉터리 백업</li><br>
    <li data-icon="2️⃣"> 메인 서버의 로그 백업</li><br>
    <li data-icon="3️⃣"> 로그 모니터링 서비스</li><br>
  </ul>

</div>
{%endblock%}
</body>
</html>

mysite/templates/monitor/log.html
{% extends 'base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
</head>
<body>
{% block content %}
<div class="container">
  <h2>로그 관리</h2>
  <div class="table-responsive">
  <table class="table">
    <thead>
      <tr>
        <th>번호</th>
        <th>ReceivedAt</th>
        <th>FromHost</th>
        <th>Message</th>
        <th>수정</th>
        <th>삭제</th>
      </tr>
    </thead>
    <tbody>
{% for data in rsyslogs %}
      <tr>
        <td><a href="{% url 'monitor:detail' data.id %}">{{ data.id }}</a></td> <!-- detail의 data.id(ID)만 읽어라 -->
        <td>{{ data.ReceivedAt }}</td>
        <td>{{ data.FromHost }}</td>
        <td>{{ data.Message }}</td>
        <td><a href="{% url 'monitor:detail' data.id %}">{{ data.id }}</a></td>
        <td><a href="{% url 'monitor:detail' data.id %}">{{ data.id }}</a></td>
      </tr>
{% endfor %}
    </tbody>
  </table>
  </div>
</div>
{%endblock%}
</body>
</html>